Non volume actors
cornerstonejs/cornerstone3D-beta pull request #112
Opened 2022-05-24 17:15 UTC by Punzo

-Add API to add non Volume Actors
-Add Rotation tool
-Enable PERSPECTIVE mode for Volume Viewport

2022-05-25 12:33 UTC, sedghi commented on packages/core/examples/nonVolumeActorAPI/index.ts
> +  viewport.addActors(nonVolumeActors);
shouldn't this be `setActors`?

2022-05-25 12:38 UTC, sedghi commented on packages/core/src/RenderingEngine/Viewport.ts
> +    if (actorCheck) {
can you merge these two lines into 1 if actorCheck is not used anywhere?

2022-05-25 12:39 UTC, sedghi commented on packages/core/src/RenderingEngine/VolumeViewport.ts
> +     * (0.01, radius * 2), where the radius is radius containing all the actors
where radius is radius containing -> where radius is the radius of sphere ...?

2022-05-25 12:40 UTC, sedghi commented on packages/core/src/RenderingEngine/VolumeViewport.ts
> +     * However for the volume viewport the clipping range is set to be
it would be good to add that camera clipping range is being used in that matrix calculation

2022-05-25 12:41 UTC, sedghi commented on packages/core/src/RenderingEngine/VolumeViewport.ts
> +     */
Nice explanation, can we add this expalnation as a comment to the vtkSlabCamera where we are using the `isPerforming....`?

2022-05-25 12:42 UTC, sedghi commented on packages/core/src/RenderingEngine/vtkClasses/vtkSlabCamera.js
> +    if (model.isPerformingCoordinateTransformation) {
can you add that explanation here as well

2022-05-25 12:43 UTC, sedghi commented on packages/core/src/RenderingEngine/vtkClasses/vtkStreamingOpenGLVolumeMapper.js
> +import { cornerstoneStreamingImageVolumeLoader } from '@cornerstonejs/streaming-image-volume-loader';
why are we importing this here

2022-05-25 13:37 UTC, Punzo commented on packages/core/src/RenderingEngine/vtkClasses/vtkStreamingOpenGLVolumeMapper.js
> +import { cornerstoneStreamingImageVolumeLoader } from '@cornerstonejs/streaming-image-volume-loader';
just a wrong copy and paste

2022-05-26 11:20 UTC, Punzo commented
@sedghi ready for review

2022-05-26 13:17 UTC, sedghi commented on packages/core/examples/multiVolumeAPI/index.ts
> +import { VolumeActor } from 'core/src/types';
This is a wrong import, probably caused by autoimport

2022-05-26 13:18 UTC, sedghi commented on packages/core/examples/nonVolumeActorAPI/index.ts
> +setTitleAndDescription(
we need to add this example in the `example-info.json` so that it appears in the website

2022-05-26 13:19 UTC, sedghi commented on packages/core/examples/nonVolumeActorAPI/index.ts
> +    const parallelScale = camera.parallelScale * 0.5;
This is not random zoom

2022-05-26 13:20 UTC, sedghi commented on packages/core/examples/nonVolumeActorAPI/index.ts
> +addButtonToToolbar({
I recommend just to remove these boilerplate codes for buttons on toolbar to show how minimal is to render a nonVolume actor with all tools enabled.

2022-05-26 13:23 UTC, sedghi commented on packages/core/examples/nonVolumeActorAPI/index.ts
> +  actor.setMapper(mapper);
can we abstract these as a function like const `actor = getSphereActor(....)`

2022-05-26 13:23 UTC, sedghi commented on packages/core/examples/volumeAPI/index.ts
> +import { VolumeActor } from 'core/src/types';
same wrong import

2022-05-26 13:23 UTC, sedghi commented on packages/core/examples/volumeAPI/index.ts
> +    if (actorEntry && actorEntry.actor.isA('vtkVolume')) {
I don't think we need this check

2022-05-26 13:24 UTC, sedghi commented on packages/core/examples/volumeAPI/index.ts
> +    if (actorEntry && actorEntry.actor.isA('vtkVolume')) {
and this

2022-05-26 13:24 UTC, sedghi commented on packages/core/examples/volumeEvents/index.ts
> +import { VolumeActor } from 'core/src/types';
wrong import

2022-05-26 13:24 UTC, sedghi commented on packages/core/examples/volumeEvents/index.ts
> +    if (actorEntry && actorEntry.actor.isA('vtkVolume')) {
we don't need this check `.isA`

2022-05-26 13:28 UTC, sedghi commented on packages/core/src/RenderingEngine/VolumeViewport.ts
> +import vtkPlane from '@kitware/vtk.js/Common/DataModel/Plane';
can we move this import to top since it is extenral import

2022-05-26 13:30 UTC, sedghi commented on packages/core/src/RenderingEngine/VolumeViewport.ts
> +      activeCamera.setClippingRange(-1e6, 1e6);
can we have constants instead of magic numbers?

2022-05-26 13:32 UTC, sedghi commented on packages/core/test/volumeViewport_gpu_render_test.js
> +      registerVolumeLoader('fakeVolumeLoader', fakeVolumeLoader);
we don't need these for this test

2022-05-26 13:32 UTC, sedghi commented on packages/core/test/volumeViewport_gpu_render_test.js
> +      unregisterAllImageLoaders();
also these

2022-05-26 13:34 UTC, sedghi commented on packages/tools/examples/nonVolumeNavigationTools/index.ts
> +setTitleAndDescription(
can we rename this file to Manipulation Tools to be consistent?

2022-05-26 13:34 UTC, sedghi commented on packages/tools/examples/nonVolumeNavigationTools/index.ts
> +setTitleAndDescription(
Also the whole `nonVolumeActor` is kind of strange to me, do we mean any non-volume Actor? probably not? So I would suggest to rename this example and the one in the core to be `polyDataActor` ??

2022-05-26 13:36 UTC, sedghi commented on packages/tools/examples/nonVolumeNavigationTools/index.ts
> +run();
Same comments as the example in the core demo, we don't need any other view for sphere, and not much toolbar. In my opinion, the purpose of these example is how easy it is to render + manipulate the polyData actor in some couple of lines of code

2022-05-26 13:37 UTC, sedghi commented on packages/tools/src/tools/RotateTool.ts
> +export default class RotateTool extends BaseTool {
I think this toolName is confusing, can we rename it to TrackballRotate tool?

2022-05-26 13:37 UTC, sedghi commented on packages/tools/src/tools/RotateTool.ts
> +import { BaseTool } from './base';
can we move this import to down, since it is local import

2022-05-26 13:38 UTC, sedghi commented on packages/tools/src/tools/RotateTool.ts
> +    // NOTE: centerWorld corresponds to teh focal point in cornerstone3D
*the typo

2022-05-26 13:39 UTC, sedghi commented on packages/tools/src/tools/WindowLevelTool.ts
> +  Types,
This was intentioanl import. When we can we should import type with `import type `

2022-05-26 13:40 UTC, sedghi requested changes
See my comments.

2022-05-27 08:43 UTC, merged