Fix/threshold volume
cornerstonejs/cornerstone3D-beta pull request #117
Opened 2022-05-28 00:32 UTC by sedghi

2022-05-29 19:08 UTC, JamesAPetts requested changes
I'm not so sure about the approximation used here for point in sphere and think we probably just need to explicitly check the vector distance in smaller than some value? However, perhaps you have some rationalle for this approximation, we can discuss tomorrow.

2022-05-29 19:08 UTC, JamesAPetts commented on packages/tools/src/utilities/pointInSurroundingSphereCallback.ts
> +  // We can run the sphere equation to determine if a point is inside
Is an estimation good enough? I don't get how working this out in ijk space is useful when these dimensions could be e.g. (1,1,3) in many very common cases, you need to do all these calculations in world space, no?

2022-05-29 19:08 UTC, JamesAPetts commented on packages/tools/src/utilities/pointInSurroundingSphereCallback.ts
> +    // This will not be accurate, but it is a good first approximation.
Considering one of the dimensions can be 2-10x bigger than the others, I'm not sure this is a good approximation?

2022-05-30 13:15 UTC, sedghi commented on packages/tools/src/utilities/boundingBox/getBoundingBoxAroundShape.ts
> +    xMax = Math.min(width - 1, xMax);
xMin, xMax, .... are in IJK, we use dimensions to clip

2022-05-31 08:18 UTC, JamesAPetts approved these changes
LGTM, just some discussion points but good to go.

2022-05-31 08:18 UTC, JamesAPetts commented on packages/tools/src/utilities/boundingBox/getBoundingBoxAroundShape.ts
> +    xMax = Math.min(width - 1, xMax);
Oh so this is inclusive, looking at this again, this makes sense.

2022-05-31 20:12 UTC, merged