fix: colored images using rgba in CPU rendering #338
cornerstonejs/cornerstone3D-beta pull request #345
Opened 2023-01-05 04:38 UTC by Zaid-Safadi

flip the useRGBA in StackViewport to true in the CPU path as discussed here: https://github.com/cornerstonejs/cornerstone3D-beta/issues/338

2023-01-05 21:53 UTC, sedghi requested changes
default is true, I don't think we need to specify here (please check wado).

2023-01-06 04:31 UTC, Zaid-Safadi commented
> default is true, I don't think we need to specify here (please check wado).

I think I see where you default it to true [here ](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/createImage.js#L100)

Isn't the StackViewport in cs3d? The comment says `true` only required for cs-legacy, sorry maybe I am not understanding the comment very well but it sounds like it should have worked if we set it to false in the StackViewport.

yeah, I can remove it from the options!

```
function createImage(imageId, pixelData, transferSyntax, options = {}) {
  // whether to use RGBA for color images, default true as cs-legacy uses RGBA
  // but we don't need RGBA in cs3d, and it's faster, and memory-efficient
  // in cs3d
  let useRGBA = true;

  if (options.useRGBA !== undefined) {
    useRGBA = options.useRGBA;
  }


```

2023-01-06 04:40 UTC, sedghi commented
My comment was you don't need to have `useRGBA:true` in your changed files, since the default is true, you can just remove it

2023-01-11 03:25 UTC, Zaid-Safadi commented
> My comment was you don't need to have `useRGBA:true` in your changed files, since the default is true, you can just remove it

Lets keep it explicitly set to `true` so we are always sure it will work even if the wado library changes

2023-01-11 04:27 UTC, merged