Feat/measurement completed
cornerstonejs/cornerstone3D-beta pull request #84
Opened 2022-04-26 03:21 UTC by sedghi

2022-04-26 09:02 UTC, swederik approved these changes

2022-04-26 09:06 UTC, JamesAPetts requested changes
The stuff we got here is great for normal completion, but we've missed cancel.

Annotations persist on cancel, and we then still need to trigger the measurement completed event.

2022-04-26 12:51 UTC, JamesAPetts approved these changes
LGTM :)

2022-04-26 12:52 UTC, merged

2023-05-30 03:30 UTC, xiaoxiao5 commented
The ANNOTATION tool does not trigger events such as ANNOTATION COMPLETED
![image](https://github.com/cornerstonejs/cornerstone3D-beta/assets/32925906/af762cf6-e3a5-4127-9ec4-eef8d0d938bc)
cornerstone3D-beta-1.1.5
@sedghi